//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsWpfApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentsWpfApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муж.
        /// </summary>
        public static string ControlSexMan {
            get {
                return ResourceManager.GetString("ControlSexMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет.
        /// </summary>
        public static string ControlSexNotAppl {
            get {
                return ResourceManager.GetString("ControlSexNotAppl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string ControlSexUnknown {
            get {
                return ResourceManager.GetString("ControlSexUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жен.
        /// </summary>
        public static string ControlSexWoman {
            get {
                return ResourceManager.GetString("ControlSexWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string EditorAddress {
            get {
                return ResourceManager.GetString("EditorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Льгота.
        /// </summary>
        public static string EditorBenefit {
            get {
                return ResourceManager.GetString("EditorBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string EditorBirthDate {
            get {
                return ResourceManager.GetString("EditorBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строение.
        /// </summary>
        public static string EditorBuilding {
            get {
                return ResourceManager.GetString("EditorBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь.
        /// </summary>
        public static string EditorCommonArea {
            get {
                return ResourceManager.GetString("EditorCommonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string EditorDate {
            get {
                return ResourceManager.GetString("EditorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string EditorFirstName {
            get {
                return ResourceManager.GetString("EditorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string EditorFlat {
            get {
                return ResourceManager.GetString("EditorFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип квартиры.
        /// </summary>
        public static string EditorFlatType {
            get {
                return ResourceManager.GetString("EditorFlatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом.
        /// </summary>
        public static string EditorHouse {
            get {
                return ResourceManager.GetString("EditorHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string EditorID {
            get {
                return ResourceManager.GetString("EditorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string EditorLastName {
            get {
                return ResourceManager.GetString("EditorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь жилая.
        /// </summary>
        public static string EditorLivArea {
            get {
                return ResourceManager.GetString("EditorLivArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проживает.
        /// </summary>
        public static string EditorLivMen {
            get {
                return ResourceManager.GetString("EditorLivMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string EditorLogin {
            get {
                return ResourceManager.GetString("EditorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счётчик.
        /// </summary>
        public static string EditorMeter {
            get {
                return ResourceManager.GetString("EditorMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string EditorMiddleName {
            get {
                return ResourceManager.GetString("EditorMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string EditorName {
            get {
                return ResourceManager.GetString("EditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норматив.
        /// </summary>
        public static string EditorNorm {
            get {
                return ResourceManager.GetString("EditorNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string EditorNumber {
            get {
                return ResourceManager.GetString("EditorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string EditorPassword {
            get {
                return ResourceManager.GetString("EditorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плательщик.
        /// </summary>
        public static string EditorPayer {
            get {
                return ResourceManager.GetString("EditorPayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец оплаты.
        /// </summary>
        public static string EditorPaymentFinish {
            get {
                return ResourceManager.GetString("EditorPaymentFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало оплаты.
        /// </summary>
        public static string EditorPaymentStart {
            get {
                return ResourceManager.GetString("EditorPaymentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За месяц.
        /// </summary>
        public static string EditorPaymentTargetDate {
            get {
                return ResourceManager.GetString("EditorPaymentTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string EditorPrice {
            get {
                return ResourceManager.GetString("EditorPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена сверх.
        /// </summary>
        public static string EditorPriceAbove {
            get {
                return ResourceManager.GetString("EditorPriceAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string EditorRateEnd {
            get {
                return ResourceManager.GetString("EditorRateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата введения.
        /// </summary>
        public static string EditorRateStart {
            get {
                return ResourceManager.GetString("EditorRateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показание.
        /// </summary>
        public static string EditorReading {
            get {
                return ResourceManager.GetString("EditorReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string EditorRegistration {
            get {
                return ResourceManager.GetString("EditorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуга.
        /// </summary>
        public static string EditorService {
            get {
                return ResourceManager.GetString("EditorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населённый пункт.
        /// </summary>
        public static string EditorSettlement {
            get {
                return ResourceManager.GetString("EditorSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string EditorSex {
            get {
                return ResourceManager.GetString("EditorSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сокращение.
        /// </summary>
        public static string EditorShortName {
            get {
                return ResourceManager.GetString("EditorShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        public static string EditorStreet {
            get {
                return ResourceManager.GetString("EditorStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суффикс.
        /// </summary>
        public static string EditorSuffix {
            get {
                return ResourceManager.GetString("EditorSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string EditorSum {
            get {
                return ResourceManager.GetString("EditorSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь общая.
        /// </summary>
        public static string EditorTotalArea {
            get {
                return ResourceManager.GetString("EditorTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string EditorType {
            get {
                return ResourceManager.GetString("EditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ед. изм..
        /// </summary>
        public static string EditorUnit {
            get {
                return ResourceManager.GetString("EditorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string EditorUser {
            get {
                return ResourceManager.GetString("EditorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string EditorUserGroup {
            get {
                return ResourceManager.GetString("EditorUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лишние символы в поле.
        /// </summary>
        public static string ErrorFieldLength {
            get {
                return ResourceManager.GetString("ErrorFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет такого пользователя.
        /// </summary>
        public static string ErrorNoUsername {
            get {
                return ResourceManager.GetString("ErrorNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось выполнить операцию.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите верный пароль.
        /// </summary>
        public static string ErrorWrongPassword {
            get {
                return ResourceManager.GetString("ErrorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginLogOn {
            get {
                return ResourceManager.GetString("LoginLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учёт квартплаты.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стр..
        /// </summary>
        public static string ShortBuilding {
            get {
                return ResourceManager.GetString("ShortBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кв..
        /// </summary>
        public static string ShortFlat {
            get {
                return ResourceManager.GetString("ShortFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д..
        /// </summary>
        public static string ShortHouse {
            get {
                return ResourceManager.GetString("ShortHouse", resourceCulture);
            }
        }
    }
}
